# Generated by Django 5.1.3 on 2024-12-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('Course_id', models.CharField(max_length=110, primary_key=True, serialize=False)),
                ('Course_name', models.CharField(max_length=100)),
                ('Teacher_name', models.CharField(max_length=100)),
            ],
        ),
    ]
